{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T11:41:51.323Z"}
{"message":"Could not get Tasks","stack":"Error: Could not get Tasks\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\tasks.js:8:9)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T11:43:37.051Z"}
{"message":"Could not get Tasks","stack":"Error: Could not get Tasks\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\tasks.js:8:9)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T11:43:51.871Z"}
{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T11:44:03.876Z"}
{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T12:05:13.025Z"}
{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T12:06:30.678Z"}
{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T12:06:49.894Z"}
{"message":"Could not get the Users","stack":"Error: Could not get the Users\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\users.js:11:11)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T12:08:21.149Z"}
{"message":"Could not get Tasks","stack":"Error: Could not get Tasks\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\tasks.js:8:9)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-27T12:08:43.255Z"}
{"message":"Could not get Tasks","stack":"Error: Could not get Tasks\n    at router.get (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\tasks.js:8:9)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at module.exports (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\routes\\middleware\\auth.js:10:5)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Tavasoli\\first-app\\test 2\\vidly\\node_modules\\express\\lib\\router\\index.js:47:12)","level":"error","timestamp":"2021-10-30T08:10:16.296Z"}
